# Generated by Django 4.1.2 on 2022-11-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yomemi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfo',
            old_name='name',
            new_name='courseName',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='name',
            new_name='studentName',
        ),
        migrations.RenameField(
            model_name='teacherinfo',
            old_name='name',
            new_name='teacherName',
        ),
        migrations.AddConstraint(
            model_name='courseselect',
            constraint=models.CheckConstraint(check=models.Q(('grade', None), models.Q(('grade__gte', 0), ('grade__lte', 100)), _connector='OR'), name='CourseSelectGrade'),
        ),
    ]
