# Generated by Django 4.1.2 on 2022-11-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yomemi', '0002_rename_name_courseinfo_coursename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(default='Notice', max_length=15),
        ),
    ]
